add review rules
mapado/best-practices pull request #55
Opened 2024-09-03 11:00 UTC by potlaetitia

Nouveau comportement
On a ajoute les règles concernant la review dont on a parlé pendant le point tech.

2024-09-03 11:01 UTC, cmeiller reviewed
Ok

2024-09-03 11:02 UTC, cmeiller approved these changes
Oups 😛

2024-09-03 11:05 UTC, lnahiro approved these changes

2024-09-03 11:08 UTC, Laurie24 approved these changes

2024-09-03 12:20 UTC, jdeniau requested changes

2024-09-03 12:20 UTC, jdeniau commented on docs/common/pull-request.md
> +Ne devrait pas exister. Chaque PR relue doit être validée ou rejetée.
C'est assez hardos comme message, non ?

```suggestion
PEUT exister dans le cas de question qui mérite des échanges, mais dans l'idéal NE DEVRAIT PAS exister. Chaque PR relue DEVRAIT être validée ou rejetée.
```

2024-09-03 12:20 UTC, jdeniau commented on docs/common/pull-request.md
> +Une fois la PR corrigée, l'auteur doit "re-request" les reviewers. Si une PR comporte au moins 1 rejet, elle ne doit pas être mergée en l'état.
T'as perdu ta touche "MAJ" à partir de cette ligne ? 😄 

```suggestion
Une fois la PR corrigée, l'auteur doit "re-request" les reviewers. Si une PR comporte au moins 1 rejet, elle NE DOIT PAS être mergée en l'état.
```

2024-09-03 12:22 UTC, cmeiller commented on docs/common/pull-request.md
> +Ne devrait pas exister. Chaque PR relue doit être validée ou rejetée.
Oui, peut-être plus tourner la phrase dans le sens qu'il ne faut pas les prendre en compte pour le merge...

2024-09-03 15:04 UTC, JulienRAVIA approved these changes

2024-09-03 15:04 UTC, JulienRAVIA commented on docs/common/pull-request.md
> +Une fois la PR corrigée, l'auteur doit "re-request" les reviewers. Si une PR comporte au moins 1 rejet, elle ne doit pas être mergée en l'état.
Il doit re-request tous les viewers, ou seulement ceux qui ont fait le request change ?

2024-09-13 07:07 UTC, potlaetitia commented on docs/common/pull-request.md
> +Une fois la PR corrigée, l'auteur doit "re-request" les reviewers. Si une PR comporte au moins 1 rejet, elle ne doit pas être mergée en l'état.
Ceux qui ont fait le request change

2024-09-13 07:12 UTC, jdeniau approved these changes

2024-09-13 07:16 UTC, merged